### ISSUE TITLE
Create 'test.yml' reusable workflow

### ISSUE THREAD

**Issue by oscard0m** [octokit/.github#49]
# 📖 Description
Create a reusable test.yml workflow to be used across all the repositories of Octokit.js ecosystem.

## 🏁 Goal
1. To centralize GitHub Workflows used across repositories in Octokit so we can easily maintain them in a single point
2. To reduce the noise Renovatebot produces when a third-party GitHub Action inside our workflows has an update[^1].

[^1]: https://github.com/orgs/octokit/teams/js-community/discussions/11?from_comment=12

## 🔭 Scope
- As a first step, this re-usable workflow will support `octokit/*{.js|.ts}` only.

## 🔮 Future work
- [ ] Compose `actions/checkout` and `actions/setup-node` and evaluate the execution time (more info [here](https://github.com/octokit/.github/pull/13#issuecomment-1186016537))
- [ ] Extend this workflow to support the remaining `octokit/*` of the JS Ecosystem (more info [here](https://github.com/octokit/.github/pull/13#issuecomment-1186012070))

## 🚚 Migration Plan
WIP

## 💬 Discussion points / 🚫 Blockers
<details><summary><h3>Parametrize <code>node_versions</code> [Solved ✅]</h3></summary>
<p>

The idea would be to parametrize the `node_versions` for `strategy.matrix` but apparently, GitHub Action Inputs do not support `string[]` as an input type (see [here](https://github.community/t/can-action-inputs-be-arrays/16457), [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype) and [here](https://github.com/github-community/community/discussions/11692)).

<h4>Conclusion 🧑‍⚖️</h4>
We are using `fromJSON` helper (details [here](https://github.com/octokit/.github/pull/13#discussion_r922566626))

</p>
</details>

<details><summary><h3>Custom steps in <code>test.yml</code> [Solved ✅]</h3></summary>
<p>

Right now, most of our `test.yml` used across Octokit.js repositories have the following code:

```yaml
name: Test
jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm ci
      - run: npm test
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - run: exit 1
        if: ${{ needs.test_matrix.result != 'success' }}
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint
    if: ${{ always() }}
```

But there are some repositories which have extra steps or different steps:
- [Example workflow missing `lint` script](https://github.com/octokit/oauth-methods.js/blob/main/.github/workflows/test.yml)
- [Example workflow with extra step: `node scripts/update`](https://github.com/octokit/app-permissions/blob/bb4b7de83437e6ef5a3903f0acd790ef001f666f/.github/workflows/test.yml)
- [Example workflow with extra steps in `test_matrix` job](https://github.com/octokit/rest.js/blob/61d6a8f87733d365f23aca3952d540aa6ab063da/.github/workflows/test.yml#L32-L35)
- etc.

* What approach do we want to follow for **custom steps**?
   1. Extra `custom-test` workflows which extend a generic `test.yml`?
   2. Add extra logic to `test.yml` to give support to all the use cases?

<h4>Conclusion 🧑‍⚖️</h4>
- We want to support all the use cases by adding extra logic (more details [here](https://github.com/octokit/.github/pull/13#issuecomment-1186010553)).
- As a first step, we will focus on <code>octokit/*{.js|.ts}</code> repositories

</p>
</details>
